<a href="https://colab.research.google.com/github/yleessam/recommend/blob/main/0203_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
v = np.array([1,2,3])
w = np.array([6,-1,3])

print(v)
print(w)

[1 2 3]
[ 6 -1  3]


In [ ]:
v = np.array([1,2,3])

print(v, v.shape)

[1 2 3] (3,)


In [ ]:
w = np.array([[1,2,3]])

print(w, w.shape)

[[1 2 3]] (1, 3)


In [ ]:
u = np.array([[1], [2], [3]])

print(u, u.shape)

[[1]
 [2]
 [3]] (3, 1)


In [ ]:
v = np.array([1,3,5])
w = np.array([2,4,6])

print('v + w =',  v + w) # 덧셈

print('v - w =', v - w) # 뺄셈

v + w = [ 3  7 11]
v - w = [-1 -1 -1]


In [ ]:
v = np.array([1,3,5])
w = np.array([2,4,6])

print(4* v) # 곱셈 : 스칼라곱

print(v * w, np.multiply(v,w)) # 곱셈 : 성분곱

print(np.inner(v, w), v.dot(w)) # 내적

[ 4 12 20]
[ 2 12 30] [ 2 12 30]
44 44


In [ ]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

print(mat)
print(mat.shape) # ( 4x3 ) 행렬

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
# 행렬 연산 1
X = np.array([[3, 4, 2], [1, 3, 7]])
Y = np.array([[1, 0, 1], [2, 1, 1]])


print('X + Y =\n', X + Y, '\n') # 덧셈


print('X - Y =\n', X - Y) # 뺄셈

X + Y =
 [[4 4 3]
 [3 4 8]] 

X - Y =
 [[ 2  4  1]
 [-1  2  6]]


In [ ]:
# 행렬 연산 2

X = np.array([[3, 4, 2], [1, 3, 7]])
Y = np.array([[1, 0, 1], [2, 1, 1]])


print(3 * X) # 곱셈 : 스칼라곱


print(np.multiply(X, Y)) # 곱셈 : 성분곱

[[ 9 12  6]
 [ 3  9 21]]
[[3 0 2]
 [2 3 7]]


In [ ]:
# 행렬 연산 3

X = np.array([[1, 0, 3], [2, 1, 4]])
Y = np.array([[2, 3], [1, 2], [0, 1] ])


print(X.dot(Y)) # 행렬곱 (2x3)x(3x2)=(2x2)

[[ 2  6]
 [ 5 12]]


In [ ]:
# 전치 (Transpose)

x = np.array([[3], [4], [5]])
X = np.array([
    [1,0,3],
    [2,1,4]
])

print(x.T)
print(X.T)

[[3 4 5]]
[[1 2]
 [0 1]
 [3 4]]


In [ ]:
# 단위 행렬(Identity Matrix)

I = np.identity(6)

print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# 역행렬( Inverse Matrix)

X = np.array([
    [3,4],
    [5,6]
])

Xi = np.linalg.inv(X)
print(Xi)

print(X.dot(Xi))

[[-3.   2. ]
 [ 2.5 -1.5]]
[[ 1.0000000e+00 -8.8817842e-16]
 [ 0.0000000e+00  1.0000000e+00]]
